-- M10-T1: Insight Summaries.
--
-- Append-only, like everything else that records what was true at a
-- moment: a run is a reading of the responses as they stood, and
-- rewriting it later would make the label ("AI-generated by <model> on
-- <date>") a lie.
--
-- response_watermark and response_count together are the cache key. A
-- re-run with no new responses serves the stored output and never calls
-- the model — curiosity should not cost money (story 54).
--
-- The output is stored as text and always displayed with its model and
-- timestamp (story 53): it is analysis, never data, and the product
-- never lets the two look alike.

-- +goose Up
CREATE TABLE insight_runs (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    survey_id          uuid NOT NULL REFERENCES surveys (id),
    -- The newest response included in this run, and how many there were.
    response_watermark timestamptz,
    response_count     integer NOT NULL DEFAULT 0,
    model              text NOT NULL,
    output             text NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX insight_runs_survey_idx ON insight_runs (survey_id, created_at DESC);

-- Append-only: an insight run records what the answers said at a moment,
-- and a rewritten reading is not that.
-- +goose StatementBegin
CREATE FUNCTION reject_insight_mutation() RETURNS trigger AS $$
BEGIN
    IF current_setting('earful.purging', true) = 'on' AND TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'insight runs are append-only: % on %', TG_OP, TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER insight_runs_append_only
    BEFORE UPDATE OR DELETE ON insight_runs
    FOR EACH ROW EXECUTE FUNCTION reject_insight_mutation();

-- +goose Down
DROP TRIGGER insight_runs_append_only ON insight_runs;
DROP FUNCTION reject_insight_mutation();
DROP TABLE insight_runs;
