package http_test

import (
	"net/http"
	"net/url"
	"strings"
	"testing"

	"github.com/TryEarful/earful/internal/ai"
	"github.com/TryEarful/earful/internal/apptest"
)

// TestInsights_ReadEveryVersionAndAreLabelled is M10-T1 and story 53:
// one run spans every version of the survey, and what comes back is
// unmistakably labelled as a model's reading rather than as data.
func TestInsights_ReadEveryVersionAndAreLabelled(t *testing.T) {
	t.Parallel()
	fake := &ai.Fake{AnalyzeScript: [][]string{{
		"Themes: setup friction (most answers), fast support.\n",
		"Representative quotes:\n- \"Setup took ages\"\n",
	}}}
	app := apptest.New(t, apptest.Options{AI: fake})
	creator := app.Login(t, apptest.UniqueEmail("insights"))

	id := app.CreateSurvey(t, creator, "Insight survey", true)
	app.AddQuestion(t, creator, id, "long_text", "How did setup go?", nil)
	app.Publish(t, creator, id)
	answerSurvey(t, app, id, map[int]string{0: "Setup took ages"})
	answerSurvey(t, app, id, map[int]string{0: "Support answered in minutes"})

	// Reword and publish again, then collect one more answer: the run
	// must read all three (ADR-0001's scenario, in miniature).
	identity := app.QuestionIdentities(t, creator, id)[0]
	app.PostForm(t, creator, "/surveys/"+id+"/questions/"+identity, url.Values{
		"type": {"long_text"}, "text": {"Looking back, how did setup go?"},
	}).Body.Close()
	app.Publish(t, creator, id)
	answerSurvey(t, app, id, map[int]string{0: "Second version answer"})

	app.PostForm(t, creator, "/surveys/"+id+"/insights", nil).Body.Close()

	page := mustGet(t, creator, app.Server.URL+"/surveys/"+id+"/results")
	if !bodyContains(page, "Insight Summary") {
		t.Fatalf("no insight panel:\n%s", page)
	}
	if !bodyContains(page, "setup friction") {
		t.Errorf("the summary is not on the page:\n%s", page)
	}
	// The label is the point: model, time, and how many responses it read.
	if !bodyContains(page, "AI-generated by") || !bodyContains(page, "3 responses") {
		t.Errorf("the summary is not labelled as AI output:\n%s", page)
	}
	if !bodyContains(page, "not the answers themselves") {
		t.Errorf("the page does not distinguish analysis from data:\n%s", page)
	}

	// One call, and its prompt carried answers from both versions.
	if len(fake.AnalyzeCalls) != 1 {
		t.Fatalf("model calls = %d, want 1", len(fake.AnalyzeCalls))
	}
	prompt := fake.AnalyzeCalls[0].Prompt
	for _, want := range []string{"Setup took ages", "Second version answer", "Looking back, how did setup go?"} {
		if !strings.Contains(prompt, want) {
			t.Errorf("prompt is missing %q:\n%s", want, prompt)
		}
	}
	// Earlier wordings travel too, so the model can say when a change in
	// the question changed the answers.
	if !strings.Contains(prompt, "Earlier wordings") {
		t.Errorf("prompt does not mention the rewording:\n%s", prompt)
	}
}

// TestInsights_CacheUntilNewResponses is story 54: re-running with
// nothing new must not call the model.
func TestInsights_CacheUntilNewResponses(t *testing.T) {
	t.Parallel()
	fake := &ai.Fake{AnalyzeScript: [][]string{{"First reading."}, {"Second reading."}}}
	app := apptest.New(t, apptest.Options{AI: fake})
	creator := app.Login(t, apptest.UniqueEmail("insightcache"))

	id := app.CreateSurvey(t, creator, "Cached insights", true)
	app.AddQuestion(t, creator, id, "long_text", "How was it?", nil)
	app.Publish(t, creator, id)
	answerSurvey(t, app, id, map[int]string{0: "An answer"})

	app.PostForm(t, creator, "/surveys/"+id+"/insights", nil).Body.Close()
	if len(fake.AnalyzeCalls) != 1 {
		t.Fatalf("first run made %d calls, want 1", len(fake.AnalyzeCalls))
	}

	// Again, with nothing new: served from the stored run.
	app.PostForm(t, creator, "/surveys/"+id+"/insights", nil).Body.Close()
	if len(fake.AnalyzeCalls) != 1 {
		t.Errorf("a re-run with no new responses called the model again (%d calls)", len(fake.AnalyzeCalls))
	}
	page := mustGet(t, creator, app.Server.URL+"/surveys/"+id+"/results")
	if !bodyContains(page, "First reading.") {
		t.Errorf("the cached summary is not shown:\n%s", page)
	}

	// A new response makes the stored run stale, and the page says so
	// rather than quietly showing an out-of-date reading.
	answerSurvey(t, app, id, map[int]string{0: "A later answer"})
	page = mustGet(t, creator, app.Server.URL+"/surveys/"+id+"/results")
	if !bodyContains(page, "have arrived since this was written") {
		t.Errorf("a stale summary is not marked stale:\n%s", page)
	}

	app.PostForm(t, creator, "/surveys/"+id+"/insights", nil).Body.Close()
	if len(fake.AnalyzeCalls) != 2 {
		t.Errorf("a run after a new response made %d calls, want 2", len(fake.AnalyzeCalls))
	}
	page = mustGet(t, creator, app.Server.URL+"/surveys/"+id+"/results")
	if !bodyContains(page, "Second reading.") {
		t.Errorf("the fresh summary is not shown:\n%s", page)
	}
}

// TestInsights_PromptsCarryNoParticipantIdentity is the rule that makes
// this feature safe to offer on invited surveys: who said something is
// irrelevant to what was said, and must not reach a model.
func TestInsights_PromptsCarryNoParticipantIdentity(t *testing.T) {
	t.Parallel()
	fake := &ai.Fake{AnalyzeScript: [][]string{{"A reading."}}}
	app := apptest.New(t, apptest.Options{AI: fake})
	creator := app.Login(t, apptest.UniqueEmail("insight-privacy"))

	id := app.CreateSurvey(t, creator, "Invited insights", false)
	app.AddQuestion(t, creator, id, "long_text", "How did it go?", nil)
	app.Publish(t, creator, id)

	guest := apptest.UniqueEmail("insight-guest")
	app.PostForm(t, creator, "/surveys/"+id+"/participants", url.Values{"emails": {guest}}).Body.Close()
	app.PostForm(t, creator, "/surveys/"+id+"/participants/send", nil).Body.Close()
	link := inviteLinkTo(t, app, guest)

	participant := &http.Client{}
	page := mustGet(t, participant, link)
	form := respondForm(t, page)
	form.Set("q_"+extractAnswerFields(t, page)[0], "It went fine, thanks")
	submitAfterReadingTo(t, app, participant, strings.TrimPrefix(link, app.Server.URL), form)

	app.PostForm(t, creator, "/surveys/"+id+"/insights", nil).Body.Close()

	if len(fake.AnalyzeCalls) != 1 {
		t.Fatalf("model calls = %d, want 1", len(fake.AnalyzeCalls))
	}
	call := fake.AnalyzeCalls[0]
	if strings.Contains(call.Prompt, guest) || strings.Contains(call.System, guest) {
		t.Errorf("a participant's email address reached the model:\n%s", call.Prompt)
	}
	// The answer itself does travel — that is the whole point.
	if !strings.Contains(call.Prompt, "It went fine, thanks") {
		t.Errorf("the answer did not reach the model:\n%s", call.Prompt)
	}
}

// TestInsights_QuotaAndAbsence: exhausting the allowance reads as a
// temporary state, and with no text AI configured the panel is not
// offered at all.
func TestInsights_QuotaAndAbsence(t *testing.T) {
	t.Parallel()

	t.Run("quota", func(t *testing.T) {
		t.Parallel()
		fake := &ai.Fake{AnalyzeScript: [][]string{{"A reading."}}}
		app := apptest.New(t, apptest.Options{AI: fake, AIQuota: 1})
		creator := app.Login(t, apptest.UniqueEmail("insight-quota"))
		id := app.CreateSurvey(t, creator, "Quota insights", true)
		app.AddQuestion(t, creator, id, "long_text", "How was it?", nil)
		app.Publish(t, creator, id)
		answerSurvey(t, app, id, map[int]string{0: "An answer"})

		app.PostForm(t, creator, "/surveys/"+id+"/insights", nil).Body.Close()
		answerSurvey(t, app, id, map[int]string{0: "Another answer"})

		resp := app.PostForm(t, creator, "/surveys/"+id+"/insights", nil)
		body := apptest.ReadBody(t, resp)
		resp.Body.Close()
		if !bodyContains(body, "used its AI allowance for today") {
			t.Errorf("quota refusal is not readable:\n%s", body)
		}
		if len(fake.AnalyzeCalls) != 1 {
			t.Errorf("a refused run reached the model (%d calls)", len(fake.AnalyzeCalls))
		}
	})

	t.Run("no provider", func(t *testing.T) {
		t.Parallel()
		app := apptest.New(t, apptest.Options{})
		creator := app.Login(t, apptest.UniqueEmail("insight-none"))
		id := app.CreateSurvey(t, creator, "No AI insights", true)
		app.AddQuestion(t, creator, id, "long_text", "How was it?", nil)
		app.Publish(t, creator, id)
		answerSurvey(t, app, id, map[int]string{0: "An answer"})

		page := mustGet(t, creator, app.Server.URL+"/surveys/"+id+"/results")
		if bodyContains(page, "Insight Summary") {
			t.Errorf("the insight panel was offered with no provider configured:\n%s", page)
		}
	})
}
