// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strconv"

// OwlMood is which face the owl makes. Each has one kind of moment, and
// docs/style-guide.md lists where each appears and where the owl never
// does: next to data, charts, admin tools and failures that cost someone
// something.
type OwlMood string

const (
	// OwlNeutral is the mark itself: the header, the sign in pages, an
	// empty dashboard.
	OwlNeutral OwlMood = "neutral"
	// OwlListening is drawn while someone is speaking an answer.
	OwlListening OwlMood = "listening"
	// OwlHappy is drawn when something is done: answers sent, a survey
	// published.
	OwlHappy OwlMood = "happy"
	// OwlSurprised is drawn when a link leads nowhere.
	OwlSurprised OwlMood = "surprised"
)

// owl draws the mark inline rather than as an image. The Content Security
// Policy (style-src 'self') keeps an SVG file from carrying rules of its
// own, so an <img> could not change colour with the page's theme; inline,
// every part is filled by a class the stylesheet colours. It is
// decoration: whatever it stands beside says what it means.
//
// size is the height in pixels. The listening owl is wider, to make room
// for the sound it hears.
func owl(mood OwlMood, size int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{"owl", "owl-" + string(mood)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/brand.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" viewBox=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(owlViewBox(mood))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/brand.templ`, Line: 35, Col: 28}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" width=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(strconv.Itoa(owlWidth(mood, size)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/brand.templ`, Line: 36, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" height=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(strconv.Itoa(size))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/brand.templ`, Line: 37, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" aria-hidden=\"true\" focusable=\"false\"><path class=\"owl-accent\" d=\"M25 21C22.5 18.5 21.5 16 21.5 13.5C26 14 31.5 16 36 19Z\"></path> <path class=\"owl-accent\" d=\"M71 21C73.5 18.5 74.5 16 74.5 13.5C70 14 64.5 16 60 19Z\"></path> <circle class=\"owl-body\" cx=\"48\" cy=\"52\" r=\"40\"></circle> <path class=\"owl-accent\" d=\"M13 58C20 67 30 73 33 89.1A40 40 0 0 1 9.5 62C10.5 60 11.7 58.8 13 58Z\"></path> <path class=\"owl-accent\" d=\"M83 58C76 67 66 73 63 89.1A40 40 0 0 0 86.5 62C85.5 60 84.3 58.8 83 58Z\"></path> <path class=\"owl-face\" d=\"M48 38C43 28 31 24 23 29C15 35 14 47 18 55C24 64 35 70 38 90.6A40 40 0 0 0 58 90.6C61 70 72 64 78 55C82 47 81 35 73 29C65 24 53 28 48 38Z\"></path> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch mood {
		case OwlHappy:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<path class=\"owl-lid\" d=\"M28 48Q35 39 42 48\"></path> <path class=\"owl-lid\" d=\"M54 48Q61 39 68 48\"></path> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<circle class=\"owl-accent\" cx=\"35\" cy=\"46\" r=\"9.5\"></circle> <circle class=\"owl-accent\" cx=\"61\" cy=\"46\" r=\"9.5\"></circle> <circle class=\"owl-eye\" cx=\"35\" cy=\"46\" r=\"6.8\"></circle> <circle class=\"owl-eye\" cx=\"61\" cy=\"46\" r=\"6.8\"></circle> <circle class=\"owl-glint\" cx=\"37.4\" cy=\"43.4\" r=\"2\"></circle> <circle class=\"owl-glint\" cx=\"63.4\" cy=\"43.4\" r=\"2\"></circle> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<circle class=\"owl-rim\" cx=\"48\" cy=\"52\" r=\"40\"></circle> <path class=\"owl-beak\" d=\"M44 56Q48 54.2 52 56L48.9 63Q48 64.6 47.1 63Z\"></path> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if mood == OwlSurprised {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<circle class=\"owl-mouth\" cx=\"48\" cy=\"71\" r=\"2.6\"></circle> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if mood == OwlListening {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<path class=\"owl-wave\" d=\"M93 45Q97 52 93 59\"></path> <path class=\"owl-wave\" d=\"M99 40Q105 52 99 64\"></path> <path class=\"owl-wave\" d=\"M105 35Q113 52 105 69\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func owlViewBox(mood OwlMood) string {
	if mood == OwlListening {
		return "0 0 114 96"
	}
	return "0 0 96 96"
}

func owlWidth(mood OwlMood, size int) int {
	if mood == OwlListening {
		return size * 114 / 96
	}
	return size
}

// lockup is the owl beside the wordmark, as a link. The wordmark is the
// link's name; the owl beside it is decoration.
func lockup(href string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<a class=\"brand\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 templ.SafeURL
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(href))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/brand.templ`, Line: 89, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = owl(OwlNeutral, 30).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<span class=\"wordmark\">earful</span></a>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
