// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strconv"

	"github.com/TryEarful/earful/internal/domain"
)

// thanksPicture is the picture above the thanks page's heading, as the
// survey's style chooses it (ADR-0018): the happy owl, one of the three
// drawings, the creator's own picture, or nothing. The owl and the
// drawings are decoration, as the owl always was there: the heading
// beside them says what happened. The creator's picture says what it
// shows in its own alternative text.
func thanksPicture(thanks domain.StyleThanks) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		switch {
		case thanks.Picture == domain.ThanksNone:
		case thanks.Picture == domain.ThanksImage && !thanks.Image.IsZero():
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span class=\"thanks-image\"><img class=\"js-thanks-image\" src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(styleImageURL(ctx, thanks.Image))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 22, Col: 43}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" alt=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(thanks.Alt)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 23, Col: 21}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" width=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(strconv.Itoa(thanks.Image.Width))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 24, Col: 45}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" height=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(strconv.Itoa(thanks.Image.Height))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 25, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" decoding=\"async\"></span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case thanks.Drawing():
			templ_7745c5c3_Err = thanksDrawing(thanks.Picture, 96).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			templ_7745c5c3_Err = owl(OwlHappy, 96).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

// thanksDrawing draws one of the pictures a thanks page can show in
// place of the owl. Like the owl it is inline, so that every part is
// filled by a class the stylesheet colours; unlike the owl, its colours
// are the theme's (docs/style-guide.md, "Thanks page pictures"), so it
// belongs to whichever theme the survey is drawn in. None of the three
// is an owl: a survey that carries its own mark can thank in a way that
// is not Earful's.
//
// Each is drawn on a 96 unit square, on a soft disc of the theme's
// accent, with the owl's line weight.
func thanksDrawing(kind string, size int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var7 = []any{"thanks-drawing", "thanks-drawing-" + kind, "js-thanks-drawing"}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var7...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<svg class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var7).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" data-drawing=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.ResolveAttributeValue(kind)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 49, Col: 21}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" viewBox=\"0 0 96 96\" width=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.ResolveAttributeValue(strconv.Itoa(size))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 51, Col: 28}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" height=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.ResolveAttributeValue(strconv.Itoa(size))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 52, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var11)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" aria-hidden=\"true\" focusable=\"false\"><circle class=\"drawing-disc\" cx=\"48\" cy=\"48\" r=\"44\"></circle> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch kind {
		case domain.ThanksCheck:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "  <circle class=\"drawing-fill\" cx=\"48\" cy=\"48\" r=\"27\"></circle> <path class=\"drawing-on-fill\" d=\"M36 48.5L44.5 57L61 39.5\"></path> <path class=\"drawing-spark\" d=\"M48 13.5V8.5\"></path> <path class=\"drawing-spark\" d=\"M72.4 23.6L75.9 20.1\"></path> <path class=\"drawing-spark\" d=\"M82.5 48H87.5\"></path> <path class=\"drawing-spark\" d=\"M72.4 72.4L75.9 75.9\"></path> <path class=\"drawing-spark\" d=\"M48 82.5V87.5\"></path> <path class=\"drawing-spark\" d=\"M23.6 72.4L20.1 75.9\"></path> <path class=\"drawing-spark\" d=\"M13.5 48H8.5\"></path> <path class=\"drawing-spark\" d=\"M23.6 23.6L20.1 20.1\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case domain.ThanksEnvelope:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " <path class=\"drawing-line\" d=\"M10 41H19\"></path> <path class=\"drawing-line\" d=\"M7 50H19\"></path> <path class=\"drawing-line\" d=\"M10 59H19\"></path> <rect class=\"drawing-paper\" x=\"25\" y=\"29\" width=\"58\" height=\"40\" rx=\"6\"></rect> <path class=\"drawing-stroke\" d=\"M27 33L54 53L81 33\"></path> <circle class=\"drawing-fill\" cx=\"54\" cy=\"53\" r=\"8\"></circle> <path class=\"drawing-on-fill-thin\" d=\"M50.5 53.2L53 55.6L57.6 50.6\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case domain.ThanksConfetti:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " <path class=\"drawing-star\" d=\"M48 25L53.9 40.9L70.8 41.6L57.5 52.1L62.1 68.4L48 59L33.9 68.4L38.5 52.1L25.2 41.6L42.1 40.9Z\"></path> <rect class=\"drawing-piece\" x=\"15\" y=\"21\" width=\"10\" height=\"5.5\" rx=\"2.5\" transform=\"rotate(-30 20 23.75)\"></rect> <rect class=\"drawing-piece-soft\" x=\"73\" y=\"23.25\" width=\"10\" height=\"5.5\" rx=\"2.5\" transform=\"rotate(25 78 26)\"></rect> <rect class=\"drawing-piece\" x=\"70\" y=\"66\" width=\"10\" height=\"5.5\" rx=\"2.5\" transform=\"rotate(-20 75 68.75)\"></rect> <rect class=\"drawing-piece-soft\" x=\"14\" y=\"64\" width=\"10\" height=\"5.5\" rx=\"2.5\" transform=\"rotate(35 19 66.75)\"></rect> <circle class=\"drawing-piece-soft\" cx=\"48\" cy=\"14\" r=\"3.5\"></circle> <circle class=\"drawing-piece\" cx=\"81\" cy=\"45\" r=\"3.5\"></circle> <circle class=\"drawing-piece\" cx=\"15\" cy=\"45\" r=\"3.5\"></circle> <circle class=\"drawing-piece-soft\" cx=\"48\" cy=\"82\" r=\"3.5\"></circle> <path class=\"drawing-curl\" d=\"M29 80Q32 75 36 78T43 76\"></path> <path class=\"drawing-curl\" d=\"M56 12Q59 17 63 14T70 16\"></path>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// thanksChoicePreview is a choice's picture on the Style tab, drawn
// small, in the colours of the theme the style has saved, so a drawing
// looks as the thanks page will draw it. The creator's own picture is
// shown small where one is stored, and otherwise as a frame waiting for
// it; "none" shows an empty frame.
func thanksChoicePreview(picture string, style domain.Style) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var12 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var12 == nil {
			templ_7745c5c3_Var12 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var13 = []any{"thanks-choice-preview", themeClass(style)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var13...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<span class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var14 string
		templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var13).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var14)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "\" aria-hidden=\"true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch picture {
		case domain.ThanksOwl:
			templ_7745c5c3_Err = owl(OwlHappy, 48).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case domain.ThanksCheck, domain.ThanksEnvelope, domain.ThanksConfetti:
			templ_7745c5c3_Err = thanksDrawing(picture, 48).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case domain.ThanksImage:
			if !style.Thanks.Image.IsZero() {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<span class=\"thanks-choice-image style-logo\"><img class=\"js-thanks-choice-image\" src=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var15 string
				templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.ResolveAttributeValue(styleImageURL(ctx, style.Thanks.Image))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 114, Col: 51}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var15)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "\" alt=\"\" width=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var16 string
				templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.ResolveAttributeValue(strconv.Itoa(style.Thanks.Image.Width))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 116, Col: 53}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var16)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "\" height=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var17 string
				templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.ResolveAttributeValue(strconv.Itoa(style.Thanks.Image.Height))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/respond_thanks_picture.templ`, Line: 117, Col: 55}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var17)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\" decoding=\"async\"></span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "<svg class=\"thanks-choice-frame\" viewBox=\"0 0 48 48\" width=\"48\" height=\"48\" focusable=\"false\"><rect class=\"frame-edge\" x=\"4\" y=\"8\" width=\"40\" height=\"32\" rx=\"5\"></rect> <circle class=\"frame-mark\" cx=\"16\" cy=\"19\" r=\"4\"></circle> <path class=\"frame-mark\" d=\"M8 36L19 25L27 32L33 27L40 33V36Z\"></path></svg>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		default:
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "<svg class=\"thanks-choice-frame\" viewBox=\"0 0 48 48\" width=\"48\" height=\"48\" focusable=\"false\"><rect class=\"frame-edge frame-empty\" x=\"4\" y=\"8\" width=\"40\" height=\"32\" rx=\"5\"></rect></svg>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
