// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"
	"time"
)

const metricAICostByDay = `-- name: MetricAICostByDay :many
SELECT day, sum(tokens)::bigint AS tokens, sum(est_cost)::float8 AS cost
FROM ai_usage
WHERE day >= $1
GROUP BY day ORDER BY day
`

type MetricAICostByDayRow struct {
	Day    time.Time `json:"day"`
	Tokens int64     `json:"tokens"`
	Cost   float64   `json:"cost"`
}

func (q *Queries) MetricAICostByDay(ctx context.Context, day time.Time) ([]MetricAICostByDayRow, error) {
	rows, err := q.db.Query(ctx, metricAICostByDay, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricAICostByDayRow
	for rows.Next() {
		var i MetricAICostByDayRow
		if err := rows.Scan(&i.Day, &i.Tokens, &i.Cost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricCompletionRates = `-- name: MetricCompletionRates :one
SELECT
    coalesce(sum(count) FILTER (WHERE metric = 'start'), 0)::bigint      AS starts,
    coalesce(sum(count) FILTER (WHERE metric = 'completion'), 0)::bigint AS completions
FROM survey_stats
`

type MetricCompletionRatesRow struct {
	Starts      int64 `json:"starts"`
	Completions int64 `json:"completions"`
}

// Starts and completions across every survey, from the unlinked
// counters (ADR-0009) — never from anything joined to a response.
func (q *Queries) MetricCompletionRates(ctx context.Context) (MetricCompletionRatesRow, error) {
	row := q.db.QueryRow(ctx, metricCompletionRates)
	var i MetricCompletionRatesRow
	err := row.Scan(&i.Starts, &i.Completions)
	return i, err
}

const metricResponsesByDay = `-- name: MetricResponsesByDay :many
SELECT submitted_at::date AS day, count(*)::bigint AS count
FROM responses
WHERE submitted_at >= $1 AND deleted_at IS NULL
GROUP BY 1 ORDER BY 1
`

type MetricResponsesByDayRow struct {
	Day   time.Time `json:"day"`
	Count int64     `json:"count"`
}

func (q *Queries) MetricResponsesByDay(ctx context.Context, submittedAt time.Time) ([]MetricResponsesByDayRow, error) {
	rows, err := q.db.Query(ctx, metricResponsesByDay, submittedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricResponsesByDayRow
	for rows.Next() {
		var i MetricResponsesByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricSignupsByDay = `-- name: MetricSignupsByDay :many
SELECT created_at::date AS day, count(*)::bigint AS count
FROM users
WHERE created_at >= $1 AND deleted_at IS NULL
GROUP BY 1 ORDER BY 1
`

type MetricSignupsByDayRow struct {
	Day   time.Time `json:"day"`
	Count int64     `json:"count"`
}

func (q *Queries) MetricSignupsByDay(ctx context.Context, createdAt time.Time) ([]MetricSignupsByDayRow, error) {
	rows, err := q.db.Query(ctx, metricSignupsByDay, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MetricSignupsByDayRow
	for rows.Next() {
		var i MetricSignupsByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricTotals = `-- name: MetricTotals :one

SELECT
    (SELECT count(*) FROM users WHERE deleted_at IS NULL)::bigint      AS users,
    (SELECT count(*) FROM workspaces WHERE deleted_at IS NULL)::bigint AS workspaces,
    (SELECT count(*) FROM surveys WHERE deleted_at IS NULL)::bigint    AS surveys,
    (SELECT count(DISTINCT survey_id) FROM survey_versions)::bigint    AS published_surveys,
    (SELECT count(*) FROM responses WHERE deleted_at IS NULL)::bigint  AS responses,
    (SELECT count(*) FROM participants WHERE deleted_at IS NULL)::bigint AS participants
`

type MetricTotalsRow struct {
	Users            int64 `json:"users"`
	Workspaces       int64 `json:"workspaces"`
	Surveys          int64 `json:"surveys"`
	PublishedSurveys int64 `json:"published_surveys"`
	Responses        int64 `json:"responses"`
	Participants     int64 `json:"participants"`
}

// M9-T7: founder metrics, from our own database.
//
// Nothing here is added to a respondent page and no third-party
// analytics exists to add (ADR-0006). These are counts of the product's
// own objects, read by a super admin.
func (q *Queries) MetricTotals(ctx context.Context) (MetricTotalsRow, error) {
	row := q.db.QueryRow(ctx, metricTotals)
	var i MetricTotalsRow
	err := row.Scan(
		&i.Users,
		&i.Workspaces,
		&i.Surveys,
		&i.PublishedSurveys,
		&i.Responses,
		&i.Participants,
	)
	return i, err
}
