// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participants.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addSuppression = `-- name: AddSuppression :exec
INSERT INTO suppressions (email, reason)
VALUES ($1, $2)
ON CONFLICT (email) DO NOTHING
`

type AddSuppressionParams struct {
	Email  string `json:"email"`
	Reason string `json:"reason"`
}

func (q *Queries) AddSuppression(ctx context.Context, arg AddSuppressionParams) error {
	_, err := q.db.Exec(ctx, addSuppression, arg.Email, arg.Reason)
	return err
}

const clearParticipantInvited = `-- name: ClearParticipantInvited :exec
UPDATE participants SET invited_at = NULL WHERE id = $1
`

// Rolls a failed send back to pending so the next run retries it.
func (q *Queries) ClearParticipantInvited(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearParticipantInvited, id)
	return err
}

const importParticipant = `-- name: ImportParticipant :execrows

INSERT INTO participants (survey_id, email, token_hash)
VALUES ($1, $2, $3)
ON CONFLICT (survey_id, email) DO NOTHING
`

type ImportParticipantParams struct {
	SurveyID  uuid.UUID `json:"survey_id"`
	Email     string    `json:"email"`
	TokenHash []byte    `json:"token_hash"`
}

// M4-T3/T4: participants, invites, suppressions.
// ON CONFLICT keeps re-imports and duplicate rows in one paste idempotent
// (M4-T3: duplicate email import deduped). The token minted here is a
// placeholder; the real one is minted at send time, because only the hash
// is ever stored and the emailed link needs the raw token.
func (q *Queries) ImportParticipant(ctx context.Context, arg ImportParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, importParticipant, arg.SurveyID, arg.Email, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listParticipants = `-- name: ListParticipants :many
SELECT p.id, p.survey_id, p.email, p.token_hash, p.invited_at, p.bounced_at, p.submitted_at, p.created_at, p.deleted_at, (s.email IS NOT NULL)::boolean AS suppressed
FROM participants p
LEFT JOIN suppressions s ON s.email = p.email
WHERE p.survey_id = $1 AND p.deleted_at IS NULL
ORDER BY p.created_at, p.email
`

type ListParticipantsRow struct {
	ID          uuid.UUID  `json:"id"`
	SurveyID    uuid.UUID  `json:"survey_id"`
	Email       string     `json:"email"`
	TokenHash   []byte     `json:"token_hash"`
	InvitedAt   *time.Time `json:"invited_at"`
	BouncedAt   *time.Time `json:"bounced_at"`
	SubmittedAt *time.Time `json:"submitted_at"`
	CreatedAt   time.Time  `json:"created_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	Suppressed  bool       `json:"suppressed"`
}

func (q *Queries) ListParticipants(ctx context.Context, surveyID uuid.UUID) ([]ListParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listParticipants, surveyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantsRow
	for rows.Next() {
		var i ListParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.SurveyID,
			&i.Email,
			&i.TokenHash,
			&i.InvitedAt,
			&i.BouncedAt,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Suppressed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markParticipantEmailBounced = `-- name: MarkParticipantEmailBounced :exec
UPDATE participants SET bounced_at = $2
WHERE email = $1 AND bounced_at IS NULL
`

type MarkParticipantEmailBouncedParams struct {
	Email     string     `json:"email"`
	BouncedAt *time.Time `json:"bounced_at"`
}

// By address across all surveys: a hard bounce means the mailbox is gone,
// not that one survey's invite failed.
func (q *Queries) MarkParticipantEmailBounced(ctx context.Context, arg MarkParticipantEmailBouncedParams) error {
	_, err := q.db.Exec(ctx, markParticipantEmailBounced, arg.Email, arg.BouncedAt)
	return err
}

const pendingInvites = `-- name: PendingInvites :many
SELECT p.id, p.survey_id, p.email, p.token_hash, p.invited_at, p.bounced_at, p.submitted_at, p.created_at, p.deleted_at FROM participants p
WHERE p.survey_id = $1
  AND p.deleted_at IS NULL
  AND p.invited_at IS NULL
  AND p.bounced_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM suppressions s WHERE s.email = p.email)
ORDER BY p.created_at
LIMIT $2
`

type PendingInvitesParams struct {
	SurveyID uuid.UUID `json:"survey_id"`
	Limit    int32     `json:"limit"`
}

// Who still needs an invite: never invited, not bounced, not suppressed.
func (q *Queries) PendingInvites(ctx context.Context, arg PendingInvitesParams) ([]Participant, error) {
	rows, err := q.db.Query(ctx, pendingInvites, arg.SurveyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.SurveyID,
			&i.Email,
			&i.TokenHash,
			&i.InvitedAt,
			&i.BouncedAt,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setParticipantTokenAndInvited = `-- name: SetParticipantTokenAndInvited :exec
UPDATE participants SET token_hash = $2, invited_at = $3 WHERE id = $1
`

type SetParticipantTokenAndInvitedParams struct {
	ID        uuid.UUID  `json:"id"`
	TokenHash []byte     `json:"token_hash"`
	InvitedAt *time.Time `json:"invited_at"`
}

func (q *Queries) SetParticipantTokenAndInvited(ctx context.Context, arg SetParticipantTokenAndInvitedParams) error {
	_, err := q.db.Exec(ctx, setParticipantTokenAndInvited, arg.ID, arg.TokenHash, arg.InvitedAt)
	return err
}
