// Package export builds a workspace archive: the "leave anytime"
// promise in SPEC.md's solution statement, and the thing that makes the
// AGPL self-hosting story real rather than theoretical.
//
// The format is documented in docs/export-format.md and versioned, and
// that document is the contract an importer will be written against
// (story 76). Two rules follow from that:
//
//   - Nothing here is lossy on purpose. Every version's questions, every
//     response pinned to the version it answered, participants for
//     invited surveys, and the survey-level counters all travel.
//   - Nothing here invents structure the product does not have. The JSON
//     mirrors the domain, so a reader who understands Earful understands
//     the file.
package export

import (
	"archive/zip"
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// FormatVersion is the contract. Bump it when the shape changes in a way
// an importer would notice, and say what changed in docs/export-format.md.
const FormatVersion = 1

// Archive is the whole export, as it appears in workspace.json.
type Archive struct {
	FormatVersion int       `json:"format_version"`
	ExportedAt    time.Time `json:"exported_at"`
	Workspace     Workspace `json:"workspace"`
	Surveys       []Survey  `json:"surveys"`
}

type Workspace struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Survey struct {
	ID           string        `json:"id"`
	Title        string        `json:"title"`
	IsAnonymous  bool          `json:"is_anonymous"`
	Status       string        `json:"status"`
	CreatedAt    time.Time     `json:"created_at"`
	CloseAt      *time.Time    `json:"close_at,omitempty"`
	ClosedAt     *time.Time    `json:"closed_at,omitempty"`
	Versions     []Version     `json:"versions"`
	Participants []Participant `json:"participants,omitempty"`
	Responses    []Response    `json:"responses"`
	Stats        []Stat        `json:"stats,omitempty"`
	// Insights are AI readings of the answers, exported with the label
	// they carry in the product: a model and a time, never presented as
	// data (story 53).
	Insights []Insight `json:"insights,omitempty"`
}

// Insight is one stored Insight Summary.
type Insight struct {
	Model         string    `json:"model"`
	GeneratedAt   time.Time `json:"generated_at"`
	ResponseCount int       `json:"response_count"`
	Output        string    `json:"output"`
	// Note is spelled out in the file itself so a reader who opens only
	// this object still knows what they are reading.
	Note string `json:"note"`
}

// InsightNote is the label every exported summary carries.
const InsightNote = "AI-generated summary of the responses, not the responses themselves."

type Version struct {
	Number      int        `json:"number"`
	PublishedAt time.Time  `json:"published_at"`
	Questions   []Question `json:"questions"`
}

type Question struct {
	// IdentityID is the Question Identity: the key that makes results
	// comparable across versions, and the key an importer must preserve.
	IdentityID string   `json:"identity_id"`
	Position   int      `json:"position"`
	Type       string   `json:"type"`
	Text       string   `json:"text"`
	Options    []string `json:"options,omitempty"`
	Required   bool     `json:"required"`
	ScaleMin   int      `json:"scale_min,omitempty"`
	ScaleMax   int      `json:"scale_max,omitempty"`
}

type Participant struct {
	Email       string     `json:"email"`
	InvitedAt   *time.Time `json:"invited_at,omitempty"`
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	BouncedAt   *time.Time `json:"bounced_at,omitempty"`
}

type Response struct {
	ID          string    `json:"id"`
	Version     int       `json:"version"`
	SubmittedAt time.Time `json:"submitted_at"`
	// DurationSecs is the only per-response metadata that exists
	// (ADR-0009). There is no IP and no user agent to export, in any
	// survey, because no such column exists.
	DurationSecs *int `json:"duration_secs,omitempty"`
	// ParticipantEmail appears for invited surveys only.
	ParticipantEmail *string `json:"participant_email,omitempty"`
	// Answers are keyed by Question Identity.
	Answers map[string]Answer `json:"answers"`
}

// Answer mirrors domain.AnswerValue: exactly one of these is set,
// according to the question's type.
type Answer struct {
	Text    string   `json:"text,omitempty"`
	Choice  string   `json:"choice,omitempty"`
	Choices []string `json:"choices,omitempty"`
	Number  *int     `json:"number,omitempty"`
	Bool    *bool    `json:"bool,omitempty"`
}

// Stat is one unlinked survey-level counter (ADR-0009). It travels so an
// export is complete, and it carries no more meaning here than it does
// in the product: a count, never a person.
type Stat struct {
	Metric string `json:"metric"`
	Bucket string `json:"bucket,omitempty"`
	Count  int    `json:"count"`
}

// CSVFile is a per-survey responses table, generated by the caller with
// the same writer the single-survey export uses — one CSV format, not
// two.
type CSVFile struct {
	Name    string
	Content []byte
}

// Build writes the zip: workspace.json, a CSV per survey, and a README
// that tells a human what they are holding.
func Build(archive Archive, csvs []CSVFile) ([]byte, error) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)

	document, err := json.MarshalIndent(archive, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("export: encode workspace.json: %w", err)
	}
	if err := writeFile(zw, "workspace.json", document); err != nil {
		return nil, err
	}
	for _, csv := range csvs {
		if err := writeFile(zw, "surveys/"+csv.Name, csv.Content); err != nil {
			return nil, err
		}
	}
	if err := writeFile(zw, "README.txt", []byte(readme(archive))); err != nil {
		return nil, err
	}
	if err := zw.Close(); err != nil {
		return nil, fmt.Errorf("export: close archive: %w", err)
	}
	return buf.Bytes(), nil
}

func writeFile(zw *zip.Writer, name string, content []byte) error {
	w, err := zw.Create(name)
	if err != nil {
		return fmt.Errorf("export: create %s: %w", name, err)
	}
	if _, err := w.Write(content); err != nil {
		return fmt.Errorf("export: write %s: %w", name, err)
	}
	return nil
}

func readme(archive Archive) string {
	return fmt.Sprintf(`Earful workspace export
=======================

Workspace: %s
Exported:  %s
Format:    version %d

What's here
-----------

workspace.json   Everything, in one documented JSON document: every
                 survey, every published version with its questions,
                 every response pinned to the version it answered, and
                 participants for invited surveys.

surveys/         One CSV per survey — the same file the survey's own
                 "Download CSV" button produces. Convenient for
                 spreadsheets; workspace.json is the complete record.
                 Where a survey has an AI Insight Summary, it sits
                 beside its CSV as a .insight.txt file, labelled with
                 the model that wrote it. It is analysis, not data.

What's deliberately absent
--------------------------

Anonymous responses carry no email address, no IP address and no device
details, because no such column exists anywhere near a response. There
is nothing here that was withheld: this is everything Earful holds.

Moving this somewhere else
--------------------------

The format is a stable, versioned contract, documented at
docs/export-format.md in the Earful repository. Question identities are
the key to preserve: they are what keeps results comparable when a
question is reworded, and an importer that discards them will silently
split one question's history in two.

Earful is AGPL-3.0. You can run it yourself: https://github.com/TryEarful/earful
`, archive.Workspace.Name, archive.ExportedAt.UTC().Format(time.RFC3339), archive.FormatVersion)
}
